name: Destroy Infrastructure

on:
  workflow_dispatch: # Dispara o workflow apenas manualmente

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: sa-east-1

      - name: Terraform Destroy
        run: |
            terraform init
            terraform plan -target=aws_eks_node_group.appNodeGroupTechChallenge -target=aws_eks_cluster.clusterTechChallenge -target=tls_certificate.thumbprint_eks -target=aws_iam_openid_connect_provider.oidc_eks -destroy
            terraform destroy -target=aws_eks_node_group.appNodeGroupTechChallenge -target=aws_eks_cluster.clusterTechChallenge -target=tls_certificate.thumbprint_eks -target=aws_iam_openid_connect_provider.oidc_eks -auto-approve